apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wealthy-gibbon-java-springboot
  janus-idp.io/tekton: wealthy-gibbon-java-springboot
  backstage.io/kubernetes-id: wealthy-gibbon-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wealthy-gibbon-java-springboot
resources: 
- deployment.yaml
- route.yaml
- service.yaml
